# setup devops toolset on current machine
setup:
	@echo "--> Setup provisioning tools"
    
# export secrets to current environmnet
# creating resources for different environments (terraform)
# removing resources for different environments (terraform)
# creating vagrant/docker/vagrantdocker/aws/etc. images for all environments for all playbooks (packer)
# provisioning using ansible directly for all environment types for all environments with use of tags (ability to just deploy/run job/do database migration/etc.) (configuration management)
