---

postgresql_cluster_reset: true
postgresql_data_directory: "/mnt/db/postgresql/{{postgresql_version}}/{{postgresql_cluster_name}}"
postgresql_listen_addresses: ["0.0.0.0"]
postgresql_pg_hba_trust_hosts: ["0.0.0.0/0"]

postgresql_databases: [
    { name: "products" },
  ]

postgresql_users: [
    { name: "my_project", pass: "{{ postgresql_users_my_project }}" },
  ]

postgresql_user_privileges: [
    { name: "my_project", db: "products" },
  ]
